# Generated by Django 3.1.7 on 2021-07-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_userpermission'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_api_group', models.CharField(max_length=100)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.user')),
            ],
            options={
                'unique_together': {('event_id', 'action_api_group', 'user_id')},
            },
        ),
    ]
