# Generated by Django 3.1.7 on 2021-07-12 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_userpermission'),
        ('event', '0002_eventpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftevent',
            name='buyer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.buyer'),
        ),
    ]
