# Generated by Django 3.1.7 on 2021-07-12 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_userpermission'),
        ('event', '0003_auto_20210712_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftevent',
            name='buyer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.buyer'),
        ),
    ]
